### ISSUE TITLE
legacy.iphub is shutting down and moving to iphub.info

### ISSUE THREAD

**Issue by artulloss** [Muqsit/ProxyBlocker#2]
Will this break this blocker, and it would be great if u updated it to work with their new api!

**Comment by artulloss** [comment]
Follow up, this is broken now 😭

**Comment by Muqsit** [comment]
Oof, I had no idea this repo made it to the first page of `legacy.iphub` google search, this was supposed to be a side project. I'll see what I can do

**Comment by artulloss** [comment]
Thank you it's kind of a necessity for my server 😭

**Comment by OGFris** [comment]
well is you still having this issue, i made my own [API](https://github.com/OGFris/ProxyCheckerAPI) and also a plugin for it which you can find here: [ProxyChecker](https://github.com/SpecterTeam/ProxyChecker) (this isn't meant to be an ad, it's just an alternative)

**Comment by artulloss** [comment]
Thank's for deleting that, I have a working version of this now, I could ask Cortex if I can pr it.

**Comment by artulloss** [comment]
Made my own 👌
